on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n containerrueba -g containerruebaa197-rg --location "South Central US" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n containerrueba --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n containerrueba --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n containerrueba --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: containerrueba.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t containerrueba.azurecr.io/clusterk1:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push containerrueba.azurecr.io/clusterk1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_clusterk1_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep cluster-k196e8 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace cluster-k196e8`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: cluster-k196e8
        container-registry-url: containerrueba.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: clusterk1dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: cluster-k196e8
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          containerrueba.azurecr.io/clusterk1:${{ github.sha }}
        imagepullsecrets: |
          clusterk1dockerauth   
